### ISSUE TITLE
Add deblobbed logo

### ISSUE THREAD

**Issue by janriemer** [commons-rs/serde-deblobbed#1]
Hello there 👋 

I think this project deserves a logo - so I made one.

![deblobbed_logo](https://github.com/commons-rs/serde-deblobbed/assets/8432168/2285fd4e-bb5a-4989-9270-1c57152f56f7)

The logo shows a crossed out blob emoji as an svg. Feel free to use it under whatever license you see fit.   
The original logo that consists of the blob emoji only (without the cross) originates from Google under the following license:

_By Google - https://github.com/googlei18n/noto-emoji/blob/bf295c4/svg/emoji_u1f603.svg, Apache License 2.0, https://commons.wikimedia.org/w/index.php?curid=62004575_

**Comment by decathorpe** [comment]
Thanks! This is a funny idea for a logo, my kind of humour :) However, I intend to delete this repo again soon, since the controversial change in serde was reverted - versions 1.0.185+ no longer ship the precompiled binary:

https://github.com/serde-rs/serde/pull/2590

**Comment by janriemer** [comment]
Thank you for the link and info. Happy the issue has gotten resolved. 🙂 

Also thank you for taking action by forking and not just complaining. I've seen so many people complain (and even getting personal).

Glad you like the logo. 😄 Let's hope we __won't__ find use for it in the future. 😉
